"""empty message

Revision ID: 554a51c9579f
Revises: a93e8263a628
Create Date: 2023-08-24 11:41:41.486697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '554a51c9579f'
down_revision = 'a93e8263a628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nameproduct', sa.String(length=100), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('nameproduct')

    # ### end Alembic commands ###
